#!/bin/sh
exec 2>&1

if [ ! -e /home/electrum/electrum.conf ]; then
  cp /etc/service/electrum/electrum.conf.default /home/electrum/electrum.conf
fi

exec su electrum -c 'python /electrum/run_electrum_server.py --conf /home/electrum/electrum.conf'
